### 环境变量
@baseUrl = http://127.0.0.1:10020
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTdkOGJhODJhOWE4Nzg5YWQyMjQ1NiIsImFjY291bnQiOiJyb2NreXNoaTE5OTNAZ21haWwuY29tIiwibmlja19uYW1lIjoiUm9ja3kgc2hpIiwidXNlcl90eXBlIjoyLCJpYXQiOjE3NzIyNjU1NDIsImV4cCI6MTc3Mjg3MDM0Mn0.u5-uQcg-nNcXI3CtNImg89wwSG_wkQVknrcdP9l4rcQaEm22QxHtQbiqYSpdTwVhgWjeIJoOt7SjMVSsi0XN-E33fMZYOIK9A9S1qMwOSIXwL2LvmMP9F6D-Z6pyKJLw0LIp0CQ3W3OOrAkhscCSPReoVJSRuIL-MGNinQM1Za4

###
# POST /home/data_agent/link/submit
# 提交链接解析，返回任务 UUID
POST https://sit-aita.guardforceai.com/chat/home/data_agent/link/submit
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "link": "https://www.xiaohongshu.com/explore/69894558000000001a0289ed?app_platform=android&ignoreEngage=true&app_version=9.19.4&share_from_user_hidden=true&xsec_source=app_share&type=normal&xsec_token=CBpakbZeCVNNo0OzvvqEJy5gbd2aufGVqIrop0JbiYxEM=&author_share=1&shareRedId=ODw7RTM-PU42NzUyOTgwNjdIOTdGSkdN&apptime=1772171542&share_id=063fc8b9dbcb4c7ea0853aabaf87a492&share_channel=copy_link&appuid=669e099e000000001e00bead&xhsshare=CopyLink"
}

